# Cluster config to create the kubernetes cluster
# eksctl create cluster -f eks_cluster_config.yaml
# All the values are dummies.. Have to replace with proper ones prior updating
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: ap-south-1
  version: "1.20"

vpc:
  id: "vpc-0a7e986d70910cfea"
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      ap-south-1a:
        id: "subnet-014b5098734fdee8d"
      ap-south-1b:
        id: "subnet-0e73e90b733ba4b93"
      ap-south-1c:
        id: "subnet-0040a579a90d12901"
    public:
      ap-south-1a:
        id: "subnet-0e871951cc34ed8d8"
      ap-south-1b:
        id: "subnet-0bd3ff817160f4676"
      ap-south-1c:
        id: "subnet-0b2132d251a914455"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
    roleName: eksctl-cluster-autoscaler-role
    roleOnly: true
managedNodeGroups:
  - name: managed-ng-1
    # EC2 tags required for cluster-autoscaler auto-discovery
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev-cluster: "owned"
    instanceType: t3.large
    securityGroups:
      attachIDs: 
        - "sg-04607f5bbc4b9fd30"
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 80
